CREATE TABLE IF NOT EXISTS property (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_name VARCHAR(255),
    property_location VARCHAR(255),
    manager_username VARCHAR(255) NOT NULL,
    CONSTRAINT fk_property_manager_username FOREIGN KEY (manager_username) REFERENCES user(username)
);

INSERT INTO property (property_name, property_location, manager_username) VALUES('Hotel', 'Alaska', 'manager');
INSERT INTO property (property_name, property_location, manager_username) VALUES('House number 1', 'California', 'manager');
INSERT INTO property (property_name, property_location, manager_username) VALUES('House number 2', 'Colorado', 'manager');